 if [ "$color_prompt" = yes ]; then
     PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
 else
     #PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
     #PS1='${debian_chroot:+($debian_chroot)}\w\[\033[01;33m\]\$\[\033[00m\] '
     #PS1='${debian_chroot:+($debian_chroot)}\[\e[30;47m\]\w\$\[\033[00m\] '
     #PS1='${debian_chroot:+($debian_chroot)}\[\033[4m\]\w\$\[\033[00m\] '
     PS1='${debian_chroot:+($debian_chroot)}\w\[\033[30;43m\]\$\[\033[00m\] '
 fi
